apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-server
  name: argocd-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-server
  name: argocd-server
spec:
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      containers:
        - command:
          - argocd-server
          - --insecure
          name: argocd-server