apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-redis
  name: argocd-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd-redis
  name: argocd-redis
spec:
  template:
    metadata:
      labels:
        app: argocd-redis