apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-repo-server
  name: argocd-repo-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd
  name: argocd-repo-server
spec:
  template:
    metadata:
      labels:
        app: argocd-repo-server