apiVersion: v1
kind: Secret
metadata:
  name: myrepo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Chuchodavids/m0n3t
  name: m0n3
  type: kustomize